### ISSUE TITLE
Switch the license to GPLv3

### ISSUE THREAD

**Issue by gaudecker** [gaudecker/qt-json#15]
License of the class should be changed to GPLv3

**Comment by george-hopkins** [comment]
I just hit the same problem as @rla. Do you have any plans to change the license?

Otherwise, most projects are actually not able to use the library. In recent years, a lot of projects were licensed under MIT/BSD-like licenses which did not do them any harm. Instead they could even profit from contributions written by employed workers.

**Comment by martinrotter** [comment]
Some people just want avoid commercial sphere. Double licensing would not make any harm, though.

**Comment by rla** [comment]
@george-hopkins for us this was solved by switching to Qt5 that includes native JSON parser. Unless your project reads lots of files, switching is not that bad. Of course, if you still use Qt4, you do not have that choice.
